### PR TITLE
#151991928 houndci integration

### PR DESCRIPTION
**Pull request by zachang**
#### What does this PR do?
Integrates HoundCI to codebase
#### Description of Task to be completed?
HounCI basically checks that style guides are adopted always. 
* Login to (https://houndci.com) while logged-in to github
* Add a .hound.yml file for custom configuration e.g eslint
+ Activate project repo on HoundCI website
#### How should this be manually tested?
+ Push and raise PR request and check repo if any error is flag by HoundCI
#### Any background context you want to provide?
+ None yet
#### What are the relevant pivotal tracker stories?
`#151991928`
#### Questions:
+ None yet

### CODE REVIEW

**Review by temilaj — CHANGES_REQUESTED** [review]
You have two commits with the same message. Why is that?

**Comment by zachang** [comment]
The commits have been squashed into one.

**Comment by zachang** [comment]
The commits have been squashed into one.

**Review by temilaj — CHANGES_REQUESTED** [review]
I'm curios to know why you made changes to the package.json file?

**Pull request merged**
