### PR TITLE
#151991927 Integrate Travis-CI with readMe badge

### PR DESCRIPTION
**Pull request by tosmak16**
#### What does this PR do?
It integrates Travis-CI with readMe badge
#### Description of Task to be completed?
**Integrate TravisCi with readme badge by doing the following:**
* Synchronize TravisCI with mont-blanch-cfc repo
* Create .travis.yml file in local repository 
* push to Github
* Copy build pass markdown from TravisCi
* Add markdown to readme file as readme badge
* push to Github
#### How should this be manually tested?
* Log into travisCI with Github account
* Get admin access to mont-blanch-cfc repo if need be 
* Sync Github account to TravisCI
* Click mont-blanch-cfc repo link on Travis CI
* Click branches
* Click chore/151991927/integrate-travisCI 
#### Any background context you want to provide?
none for now.
#### What are the relevant pivotal tracker stories?
#151991927
#### Screenshots
image

image

#### Questions:
none for now

### CODE REVIEW

**Review by temilaj — COMMENTED** [review]
How did you get the tests to work here?

**Comment by tosmak16** [comment]
It was throwing an error related to a particular word called "Article" in the test folder. when i checked through the code i discover that it is not really relevant. so i removed it.

**Comment by temilaj** [comment]
@tosmak16 Yes, but this isn't showing in the `Files changed` tab. Why is that?

**Review by temilaj — CHANGES_REQUESTED** [review]
You have merge conflicts. Please resolve them

**Comment by tosmak16** [comment]
Changes have been made

**Pull request closed without merging**
